CREATE TABLESPACE TS_USER25
    DATAFILE 'E:\ORACLE\DATA\TS_USER_25.dbf' SIZE 1024M
    AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
    SEGMENT SPACE MANAGEMENT AUTO; 
    
CREATE USER MIJIN
    IDENTIFIED BY MIJIN
    DEFAULT TABLESPACE TS_USER25
    TEMPORARY TABLESPACE TEMP;
    
select * 
from dba_tablespaces;    

GRANT CONNECT,RESOURCE,DBA TO MIJIN;    